/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_2_edd.Graficos;

import com.mycompany.proyecto_2_edd.ListaTablas.ListaTabla;
import com.mycompany.proyecto_2_edd.Listas.Tabla;
import java.awt.BorderLayout;

/**
 *
 * @author jose
 */
public class panelPrincipal extends javax.swing.JPanel {
    
    private ListaTabla tablas;
    /**
     * Creates new form panelPrincipal
     */
    public panelPrincipal(ListaTabla tablas) {
        this.tablas = tablas;
        initComponents();
        agregarBotones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    public void agregarBotones(){
        this.setLayout(new BorderLayout());
        BotonesDeCarga nuevo = new BotonesDeCarga(tablas);
        this.add(nuevo,BorderLayout.EAST);
        TablaPrueba nuevaTabla = new TablaPrueba(new Tabla());
        this.add(nuevaTabla,BorderLayout.CENTER);
        BotonesManuales manuales = new BotonesManuales(this);
        this.add(manuales,BorderLayout.WEST);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
