/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_2_edd.Graficos;

import com.mycompany.proyecto_2_edd.ListaTablas.ListaTabla;
import com.mycompany.proyecto_2_edd.Listas.Tabla;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author jose
 */
public class panelPrincipal extends javax.swing.JPanel {
    
    private ListaTabla tablas;
    private JPanel centro;
    private JPanel derecha;
    private JPanel izquiera;
    private JPanel arriba;
    private JPanel abajo;

    /**
     * Creates new form panelPrincipal
     */
    public panelPrincipal(ListaTabla tablas) {
        this.tablas = tablas;
        centro = new JPanel();
        derecha = new JPanel();
        izquiera = new JPanel();
        arriba = new JPanel();
        abajo = new JPanel();
        derecha.setLayout(new CardLayout());
        izquiera.setLayout(new CardLayout());
        centro.setLayout(new CardLayout());
        arriba.setLayout(new CardLayout());
        abajo.setLayout(new CardLayout());
        initComponents();
        this.setLayout(new BorderLayout());
        agregarBotones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    public void agregarBotones(){
        
        BotonesDeCarga nuevo = new BotonesDeCarga(tablas);
        derecha.add(nuevo);
        BotonesManuales manuales = new BotonesManuales(this,tablas);
        izquiera.add(manuales);
        botonesArriba arribaB = new botonesArriba(tablas,this);
        arriba.add(arribaB);
        agregar();
        
    }
    

    public JPanel getCentro() {
        return centro;
    }
 public void agregar() {
        this.add(centro, BorderLayout.CENTER);
        this.add(derecha, BorderLayout.EAST);
        this.add(izquiera, BorderLayout.WEST);
        this.add(arriba, BorderLayout.NORTH);
        this.add(abajo, BorderLayout.SOUTH);
        this.setVisible(false);
        this.setVisible(true);
    }
    public void setCentro(JPanel centro) {
        this.setVisible(false);
        this.centro.setVisible(false);
        this.centro = new JPanel();
        this.centro.setLayout(new CardLayout());
        this.centro.add(centro);
        this.centro.setVisible(true);
        agregar();
    }

    public JPanel getDerecha() {
        return derecha;
    }

    public void setDerecha(JPanel derecha) {
        this.derecha = derecha;
    }

    public JPanel getIzquiera() {
        return izquiera;
    }

    public void setIzquiera(JPanel izquiera) {
        this.izquiera = izquiera;
    }

    public JPanel getArriba() {
        return arriba;
    }

    public void setArriba(JPanel arriba) {
        this.arriba = arriba;
    }

    public JPanel getAbajo() {
        return abajo;
    }

    public void setAbajo(JPanel abajo) {
        this.abajo = abajo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
