/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_2_edd.Graficos;

/**
 *
 * @author jose
 */
public class TablaCrear extends javax.swing.JPanel {

    /**
     * Creates new form TablaCrear
     */
    public TablaCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setText("Nombre");
        add(jLabel1);
        jLabel1.setBounds(300, 40, 55, 15);
        add(nombre);
        nombre.setBounds(470, 40, 133, 23);

        jLabel2.setText("Clave");
        add(jLabel2);
        jLabel2.setBounds(300, 90, 38, 15);
        add(jTextField1);
        jTextField1.setBounds(470, 80, 133, 23);

        jLabel3.setText("Atributos ");
        add(jLabel3);
        jLabel3.setBounds(390, 170, 70, 15);

        jButton1.setText("Confirmar nombre y clave");
        add(jButton1);
        jButton1.setBounds(350, 130, 209, 31);

        jLabel4.setText("Nombre");
        add(jLabel4);
        jLabel4.setBounds(300, 210, 55, 15);

        jLabel5.setText("Tipo");
        add(jLabel5);
        jLabel5.setBounds(300, 250, 30, 15);
        add(jTextField2);
        jTextField2.setBounds(440, 200, 144, 23);

        jButton2.setText("Agregar atributo");
        add(jButton2);
        jButton2.setBounds(380, 290, 180, 31);

        jButton3.setText("Crear tabla");
        add(jButton3);
        jButton3.setBounds(380, 430, 110, 31);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "double", "string", "float", "char", "long", "integer" }));
        add(jComboBox1);
        jComboBox1.setBounds(440, 250, 144, 25);

        jLabel6.setText("Referncia");
        add(jLabel6);
        jLabel6.setBounds(300, 360, 67, 15);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(380, 360, 75, 25);

        jButton4.setText("Agregar ");
        add(jButton4);
        jButton4.setBounds(530, 350, 110, 31);

        jLabel7.setText("Precione Agregar si decea hacer una referencia a otra tabla");
        add(jLabel7);
        jLabel7.setBounds(250, 330, 426, 15);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
