/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_2_edd.Graficos;

/**
 *
 * @author jose
 */
public class TablaCrear extends javax.swing.JPanel {

    /**
     * Creates new form TablaCrear
     */
    public TablaCrear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 44, -1, -1));
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 133, -1));

        jLabel2.setText("Clave");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 85, -1, -1));

        jTextField1.setText("Clave");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 81, 133, -1));

        jLabel3.setText("Atributos ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jButton1.setText("Confirmar nombre y clave");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 127, -1, -1));

        jLabel4.setText("Nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 207, -1, -1));

        jLabel5.setText("Tipo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 249, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 203, 144, -1));

        jButton2.setText("Agregar atributo");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jButton3.setText("Crear tabla");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 428, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "int", "double", "string", "float", "char", "long", "integer" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 249, 144, -1));

        jLabel6.setText("Referncia");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 362, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 357, 75, -1));

        jButton4.setText("Agregar ");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jLabel7.setText("Precione Agregar si decea hacer una referencia a otra tabla");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 333, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
